package org.sample.domain.entities;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;
import java.util.Set;

@Entity
public class Book {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto generated by DBS
    public Long id;

    @NotBlank
    public String name;

    // Need the cascade type so we can also create a bunch of users - however this is business code smell - it should be removed (sake of the example in bidirectional)
    @ManyToMany(mappedBy = "books", cascade = CascadeType.PERSIST)
    public Set<User> users;

}
