package org.sample.domain.entities;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;
import java.util.Set;

@Entity
public class Book {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto generated by DBS
    public Long id;

    @NotBlank
    public String name;

    @ManyToMany(mappedBy = "books")
    public Set<User> users;

}
