package org.sample.domain.entities;

import com.fasterxml.jackson.annotation.JsonInclude;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

@NamedEntityGraph(
        name = "City.country",
        attributeNodes = {
                @NamedAttributeNode("name"),
                @NamedAttributeNode("country"),
        }
)
@JsonInclude(JsonInclude.Include.NON_NULL)
@Entity
public class City {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto generated by DBS
    public Long id;

    @NotNull
    public String name;

    @ManyToOne(fetch = FetchType.LAZY) // this is the default fetch type
    @JoinColumn(name = "country_id", nullable = false)
    public Country country;

}
