package org.sample.domain.entities;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

@NamedEntityGraph(
        name = "city-entity-graph",
        attributeNodes = {
                @NamedAttributeNode("name"),
                @NamedAttributeNode("country"),
        }
)
@Entity
public class City {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto generated by DBS
    public Long id;

    @NotNull
    public String name;

    @ManyToOne(fetch = FetchType.EAGER) // this is the default fetch type
    @JoinColumn(name = "country_id", nullable = false)
    public Country country;

}
