package org.sample.domain.entities;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

@Entity
public class City {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto generated by DBS
    public Long id;

    @NotNull
    public String name;

    @ManyToOne
    @JoinColumn(name = "country_id", nullable = false)
    public Country country;

}
