package org.sample.domain.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.Set;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler", "fieldHandler"}, ignoreUnknown = true)
@NamedEntityGraph(name = "country_entity_graph",
        attributeNodes = {
                @NamedAttributeNode("name"),
                @NamedAttributeNode("cities")
        }
)
@Entity
public class Country {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto generated by DBS
    public Long id;

    @NotNull
    public String name;

    @OneToMany(mappedBy = "country")
    @JsonIgnore
    public Set<City> cities;
}
